---
title: Facilitating cross-cultural projects
authors:
  - Elsa Culler
  - Nate Quarderer
learning-goals:
  - Practice active listening
  - Define Ethical Space
  - Identify the Groan Zone
date: last-modified
keywords:
  - "Project-based Learning"
  - "Cultural Relevance"
---

Meaningful projects may be the key to classroom inclusion — but meaningful work is often tough, emotional work. As STEM educators we aren’t usually trained to productively channel student’s emotions and experiences. In this session we will cover three frameworks that we use at the Earth Data Science Innovation and Inclusion Lab to foster innovative, cross-cultural science teamwork: active listening, ethical space, and the “groan zone”. Active listening is an important skill for constructing a classroom environment where team members can express potentially traumatic or upsetting experiences that motivate their learning and inquiry goals. Ethical space is a framework for collaborating across cultures while respecting all team-members' contributions and sovereignty. Finally, the “groan zone” refers to the fact that learning and innovating is inherently uncomfortable, and teams who can’t tolerate that discomfort miss out on the juicy and impactful ideas and understanding that lies on the other side. In this workshop, we will present these three frameworks, practice them using role play, and discuss some ways they can be used to facilitate cross-cultural student projects.

## Session slides

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSWc40kns6IDHyHxw7KsGUyElL2iBWm_eEWwF2WaJy2FWcT3GKLwWWbX-2kjvXBkyIH42kPCK550uaV/embed?start=false&loop=false&delayms=60000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>