---
title: "ESIIL Data Short Course"
subtitle: "Get started teaching Earth Data Science"
authors:
  - Elsa Culler
  - Nate Quarderer
date: last-modified
keywords:
  - "Earth Data Science"
  - "STEM Education"
---

## What is the ESIIL Data Short Course?
Through this 4-week, project-based data short course, Earth Science educators and leaders will learn how to inclusively engage learners in:

  - Understanding and unlocking the potential of EDS empower their communities
  - Contributing to  sustainable, collaborative EDS projects
  - Telling their community’s data stories

Participants will engage in a series of trainings that prepare them to include open science (Python) and collaboration tools (GitHub, including GitHub Classroom, GitHub Codespaces, and GitHub Pages) into their curriculum or existing research model. We will emphasize working with key types of environmental data (time series, vector, and raster), and using cloud computing to enhance access to Earth Data Science education. At the end of the data short course, participants will be expected to create a lesson that applies lessons learned to a class or project that they are currently working on.

## Who is this for?
Lessons will be geared toward educators and early careerists interested in incorporating EDS teaching into their existing programs and curricula (biology, ecology, geography, etc.). 

## When and how can you participate?
All trainings  will be available as both:
  1) live online workshops and 
  2) materials for self-paced learning

Building on participation in the short course, we will establish an ongoing open community forum, help desk, and office hours to support continued learning and capacity-building.

## What’s next? 
Our commitment to building a community of educators.This data short course is first in a series of 4 courses that will introduce participants to:

  * [Course 1](01-collaboration/): EDS community standard collaboration, education, and online publishing tools 
  * [Course 2](02-data/): Finding and working with EDS data following FAIR and CARE data principles 
  * [Course 3](03-reproducible/): Writing modular, readable, and reproducible scientific workflows
  * [Course 4](04-cyberinfrastructure/): Cyberinfrastructure skills for teaching Earth Data Science
 
Each course will provide participants with the opportunity to develop their own lessons that apply skills learned during the training. 