project:
  type: book
  output-dir: _release
  pre-render:
    - scripts/expand_templates.py
    - scripts/generate_lesson_segments.py
  render:
    - notebooks/02-flood/flood-stars.qmd
    - notebooks/02-flood/flood-download-stars.qmd
    - notebooks/03-migration/migration-stars.qmd
    - notebooks/03-migration/migration-download-stars.qmd
    - notebooks/05-vegetation/vegetation-stars.qmd
    - notebooks/05-vegetation/vegetation-download-stars.qmd

book:
  title: "ESIIL Learning Portal"
  author: "ESIIL Education"
  date: today
  chapters:
    - index.qmd
    # Stars
    - notebooks/02-flood/flood-stars.qmd
    - notebooks/02-flood/flood-download-stars.qmd
    - notebooks/03-migration/migration-stars.qmd
    - notebooks/03-migration/migration-download-stars.qmd
    - notebooks/05-vegetation/vegetation-stars.qmd
    - notebooks/05-vegetation/vegetation-download-stars.qmd

format:
  pdf:
    toc: true
    number-sections: true
    self-contained: true
