project:
  output-dir: _student
  pre-render:
    - scripts/generate_lesson_segments.py
  render:
    # # Stars
    # - notebooks/02-flood/segments-stars/
    # - notebooks/03-migration/segments-stars/
    # - notebooks/05-vegetation/segments-stars/
    # # Shortcourse
    # - notebooks/01-climate/segments-shortcourse/
    # - notebooks/05-vegetation/segments-shortcourse/
    # # EDA
    - notebooks/01-climate/segments-eda/
    - notebooks/03-migration/segments-eda/

execute:
  enabled: false
  eval: false
  cache: false
  freeze: false

format:
  ipynb:
    toc: true
    filters:
      - filters/embed-img.lua
