name: learning-portal
channels:
  - conda-forge
  - r
  - defaults

dependencies:
  # Python
  # ------
  - python=3.11
  - pip
  - ipykernel
  # Core
  - numpy
  - xarray
  - pandas
  - dask
  - earthpy
  # API
  - pystac-client # STAC
  - earthaccess # NASA images over fsspec
  - adlfs
  - dataretrieval # USGS
  # Plotting
  - seaborn
  # --- Avoid compatibility issues with bokeh and new holoviews
  - holoviews<=1.19
  - hvplot
  - geoviews>=1.10
  - jupyter_bokeh
  - folium
  - selenium
  # Spatial
  - pyproj>=3.0
  - geopandas
  - pyogrio
  - osmnx
  - rioxarray
  - regionmask
  - xarray-spatial
  # IO
  - h5netcdf
  # AI
  #- ollama
  # QA
  - flake8
  - flake8-import-order
  - black
  # pip
  - pip:
    - pygbif

  # R
  # -
  # Basics
  - r-base
  - r-essentials
  - r-irkernel
  - r-languageserver
  - r-devtools
  - r-rcurl
  - r-rcpp
  # Bilingual notebooks
  - r-reticulate
  # Spatial data
  - r-terra
  - r-sf
  - r-stars
  - r-sp
  - r-ncdf4
  # Time-series data
  - r-changepoint
  # Plotting
  - r-pals
  - r-maps
  - r-plotly
  # Display
  - r-jpeg
  - r-magick
  - r-kableextra
  # Phenocam dependencies
  - r-rjson

  # Website build
  - quarto
  - jupyter
  - yaml
  - nbformat
  - nbclient
  - jupyter-cache
  - pandoc

  # GitHub CLI
  - gh

