---
title: "ESIIL IGNITE Data Analytics"
subtitle: "Interactive Guide for New Innovators and Technologists in Environmental Data Analytics"
authors:
  - Elsa Culler
date: last-modified
---

Welcome to ESIIL IGNITE Data Analytics! If you are an environmental scientist, computer programmer, or statistician looking to get involved in the highly interdisciplinary field of Environmental Data Analytics, you're in the right place.

On this site, you'll

## How to use ESIIL IGNITE

IGNITE resources are typically built around interactive computing notebooks. We often provide starter code if you want to work things out yourself, as well as working examples in the "See our solution" dropdown. We recommend running the code as you go -- it's how our students find the most success.

## We want your contributions!

If you think we're missing something that was essential to your transition to environmental data analytics, reach out in our contribution page! We want this resource to evolve with your needs and with technological development.
