# Part 1: Overview

Higher highs, lower lows, storms, and smoke -- we're all feeling the effects of climate change. In this workflow, you will take a look at trends in temperature over time in {{< meta params.01-climate.location >}}.

::: {.content-visible when-profile="stars"}
:::: {.callout-read}
[Read about some of the effects of -- and solutions for -- climate change on the Pine Ridge Reservation southeast of Rapid City.](https://www.theguardian.com/environment/2022/dec/03/south-dakota-reservation-food-desert-residents-transforming-crop-oasis)
::::

:::: {.callout-discuss}
In a few sentences, how is climate change affecting your home? 
::::: {.content-visible when-format="ipynb"}
Write your response in the Markdown cell below.
:::::
::::
:::

::: {.content-visible when-format="ipynb"}
:::: {.cell ,markdown}
# YOUR ANSWER HERE
::::
:::

::: {.content-visible when-format="html"}
:::: {.callout-video}

::::: {.content-visible when-profile="shortcourse"}

<div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGCmAuzaio&#x2F;hzAY0BZp3ikTPyTA_QR8Cw&#x2F;watch?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGCmAuzaio&#x2F;hzAY0BZp3ikTPyTA_QR8Cw&#x2F;watch?utm_content=DAGCmAuzaio&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">DEMO: Get Started with Open Reproducible Science</a> by ESIIL

:::::

::::: {.content-visible when-profile="stars"}
<div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGD_5vNgBA&#x2F;pHWDRhcRJUaN64dED_5BSQ&#x2F;watch?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGD_5vNgBA&#x2F;pHWDRhcRJUaN64dED_5BSQ&#x2F;watch?utm_content=DAGD_5vNgBA&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">Get Started with Open Reproducible Science (Stars)</a> by ESIIL

:::::

::::: {.content-visible when-profile="foundations"}

:::::: {.panel-tabset}
### Plot Data
<div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGQg3ELeQc&#x2F;ayLtU4vCeRAUDTZcciewqg&#x2F;watch?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGQg3ELeQc&#x2F;ayLtU4vCeRAUDTZcciewqg&#x2F;watch?utm_content=DAGQg3ELeQc&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">Climate Coding Challenge Video 1</a> by Earth Lab

### Part 2: Trend Line
<div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGRIy3kSmE&#x2F;xLIn0w09bsaHvJrWVqvdSw&#x2F;watch?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGRIy3kSmE&#x2F;xLIn0w09bsaHvJrWVqvdSw&#x2F;watch?utm_content=DAGRIy3kSmE&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">DEMO: Climate Part 2 (EDA)</a> by Earth Lab

### Part 3: Portfolio
<div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGRI_qLFQ4&#x2F;Rt_loLnzC_XHHOEwgk3MKA&#x2F;watch?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGRI_qLFQ4&#x2F;Rt_loLnzC_XHHOEwgk3MKA&#x2F;watch?utm_content=DAGRI_qLFQ4&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">DEMO: Climate Part 3 (EDA)</a> by Earth Lab

:::::

::::
:::

## What the fork?! Who wrote this?

Below is a scientific Python workflow. But something's wrong -- The code won't run! Your task is to follow the instructions below to **clean and debug** the Python code below so that it runs.

::: {.callout-tip}
Don't worry if you can't solve every bug right away. We'll get there! If you are working on one bug for more than about 10 minutes, it's time to ask for help. 
:::

At the end, you'll **repeat the workflow** for a location and measurement of your choosing.

Alright! Let's clean up this code.