---
title: Climate coding challenge, Part 0
subtitle: Names and Types in Python
format:
  html: default
  ipynb:
    output-file: "!START HERE: Warm-up with names and types in Python"
---

## Human-readable and Machine-readable

When writing open, reproducible scientific workflows, it is always important to make sure that:

  1. all collaborators can understand what's going on
  2. any commands you give to a computer are clear and unambiguous

We call these two (sometimes competing) goals **human-readability** and **machine-readability**.

::: {.callout-note icon="false"}
## {{< fa glasses size=large >}} Further reading

Read [our textbook chapter about organizing open reproducible science projects](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/get-started-open-reproducible-science/best-practices-for-organizing-open-reproducible-science/).
:::

::: {.cell .markdown}
:::: {.callout-important icon="false"}
## {{< fa pencil size=large >}} Human-readable and Machine-readable

- [ ] Create a new Markdown cell below this one using the <kbd>ESC</kbd> + <kbd>b</kbd> keyboard shortcut.
- [ ] In the new cell, answer the following question in a Markdown **quote**: Does this Jupyter Notebook file have a machine-readable name? Explain your answer.

::::: {.content-visible when-profile="graded"}
Rubric:

| Task | Max Points | Points | Comments |
|------|------------|--------|----------|
| Create Markdown cell            | 1 |  |  |
| Use a quote                     | 2 |  |  |
| Thoughtful response to question | 2 |  |  |
| Easily readable                 | 1 |  |  |
:::::
::::
:::

::: {.callout-important icon="false"}
## {{< fa keyboard size=large >}} Your task: Machine-readable file names

Rename any notebooks in this folder with an **expressive and machine-readable file name**
:::