---
title: Climate coding challenge, Part 5
subtitle: Is the climate changing?
jupyter: python3
format:
  ipynb:
    output-file: "Get Started with Open Reproducible Science, Part 5!"
---

::: {.content-visible when-format="ipynb"}
First things first -- make sure to load the climate `DataFrame` you stored in the previous notebooks using Jupyter cell magic:

```{python}
# Load all stored variables
%store -r
```
:::

## Quantify how fast the climate is changing with a trend line

Global climate change causes different effects in different places when we zoom in to a local area. However, you probably noticed when you looked at mean annual temperatures over time that they were rising. We can use a technique called **Linear Ordinary Least Squares (OLS) Regression** to determine how quickly temperatures are rising on average.

Before we get started, it's important to consider that OLS regression is not always the right technique, because it makes some important assumptions about our data:

  Random error
  : Variation in temperature can be caused by many things beyond global climate change. For example, temperatures often vary with patterns of ocean surface temperatures (*teleconnections*), the most famous of which are El Niño and La Niña. By using a linear OLS regression, we're assuming that all the variation in temperature except for climate change is random.
  Normally distributed error
  : If you have taken a statistics class, you probably learned a lot about the normal, or Gaussian distribution. For right now, what you need to know is that OLS regression is useful for identifying trends in average temperature, but wouldn't be appropriate for looking at trends in daily precipitation (because most days have zero precipitation), or at maximum or minimum annual temperatures (because these are extreme values, and the normal distribution tends to underestimate the likelihood of large events).
  Linearity
  : We're assuming that temperatures are increasing or decreasing at a constant rate over time. We wouldn't be able to look at rates that change over time. For example, many locations in the Arctic had no change in temperature for a long time, because ice melt was absorbing all the extra heat. Linear OLS regression wouldn't be able to identify when the temperature rise began on its own.
  Stationarity
  : We're assuming that variation in temperature caused by things *other* than global climate change (e.g. the random error) behaves the same over time. For example, the linear OLS regression can't take increased variability from year to yearinto account -- a common effect of climate change. A common pattern we see is "global weirding", or more extreme head *and* cold, which you can observe most easily by looking at your daily data again. Does it seem to be trending up, or fanning out? OLS regression can't account for changes in random variability. Note that we're probably ok when it comes to looking at a trend line, but that we wouldn't want to trust any measures of uncertainty, like standard error, if there's clear evidence of non-stationarity.

It's pretty rare to encounter a perfect statistical model where all the assumptions are met, but you want to be on the lookout for serious discrepancies, especially when making predictions. For example, [ignoring assumptions about Gaussian error arguably led to the 2008 financial crash](https://www.wired.com/2009/02/wp-quant/).

::: {.cell .markdown}
:::: {.callout-important icon="false"}
## {{< fa pencil size=large >}} Is linear OLS regression right for your data?

- [ ] Take a look at your data. In the cell below, write a few sentences about ways your data does and does not meet the linear OLS regression assumptions.

::::: {.content-visible when-profile="graded"}
Rubric:

| Task | Max Points | Points | Comments |
|------|------------|--------|----------|
| Create Markdown cell              | 1 |  |  |
| Thoughtful response to question 1 | 2 |  |  |
| Easily readable                   | 1 |  |  |
:::::
::::
:::

::: {.callout-important icon="false"}
# {{< fa keyboard size=large >}} Your task: Regression

  - [ ] 
:::

::: {.content-visible when-format="html"}
```{python}
#| code-fold: true
#| code-summary: See our solution!
import pandas as pd
from sklearn.linear_model import LinearRegression

# Drop no data values
observations = ann_climate_df.TOBS.dropna()

# Define the dependent variable and independent variable(s)
features = observations.index.year.values.reshape(-1, 1)
response = observations

# Create a Linear Regression model
model = LinearRegression()

# Fit the model on the training data
model.fit(features, response)

# Calculate and print the metrics
print(f'Slope: {model.coef_} degrees per year')
```
:::

## Linear OLS regression in Python

::: {.callout-important icon="false"}
# {{< fa keyboard size=large >}} Your task: Regression

  - [ ] 
:::


## Plot your trend line