project:
  type: website
  output-dir: _site

website:
  title: "Logo Repro"
  sidebar:
    #### Group One
    - title: "No Logo Book"
      logo: ""
      contents:
        - index.qmd
    #### Group Two
    - title: "Logo Repro"
      logo: /img/logo.png
      logo-alt: "Logo Repro"
      logo-href: /lesson.qmd
      contents:
        - lesson.qmd

format:
  html:
    theme: cosmo
