---
title: "Fundamentals of Earth Data Analytics"
subtitle: "Get started with open reproducible science!"
authors:
  - Elsa Culler
date: last-modified
---

Welcome to Fundamentals of Earth Data Analytics, the first course in the [Earth Data Analytics -- Foundations](https://earthlab.colorado.edu/earth-data-analytics-professional-graduate-certificate) graduate certificate program at the University of Colorado Boulder. 

In this introductory, multidisciplinary course you will learn core scientific programming skills required to efficiently work with a suite of earth systems data in Python. The course provides an introduction to the scientific programming, version control and collaboration skills required for efficient workflows. Students learn programming principles like functions and basic automation using loops and syntax. Students also use Git, GitHub, Bash, and Shell for version control and collaborative coding. The course will culminate with a project rather than a final exam. This course is technical. Students will code every day and finish the course with proficiency in using Python and Jupyter notebooks. No programming experience is required to take this course!

You will find instructions on some class projects as well as background reading here in this free online textbook. If you don't see what you need here, you can also use the search bar, or visit our [classic earthdatascience.org site](http://earthdatascience.org/classic/) which contains numerous textbooks and curriculum modules.
