---
title: Climate change inquiry
subtitle: A place-based Earth Data Science activity 
authors:
  - Nate Quarderer
  - Elsa Culler
learning-goals:
  - Use open science tools (GitHub, Python, Jupyter Notebooks)
  - Download open data using an API
  - Compare temperatures at different locations
date: last-modified
keywords:
  - "Earth Data Science"
  - "STEM Education"
  - "Cultural Relevance"
---

Higher highs, lower lows, storms, and smoke -- we're all feeling the effects of climate change. As science and math educators, students are looking to us to help make sense of their changing environments. In this classroom activity, we will investigate the 2024 heat wave in the Chicago area — or any time and place that is meaningful to you or your students. This activity can support a variety of domain-specific topics in biology, physics, math, environmental science, and public health — all while teaching fundamental computational skills. As part of the activity, we will use data from the National Centers for Environmental Information, will discuss the critical link between FAIR (findable, accessible, interoperable, and reproducible) data and cultural and/or personal relevance. By the end of the session, you will have the skills and resources you need to facilitate a computational climate change activity as an element in your next class.
