# STEP 0: Import Mapping packages

Python **packages** or **libraries** let you use code written by experts around the world. Because Python is open source, lots of different people and organizations can contribute (including you!). Many contributions are in the form of **packages** which do not come with a standard Python download.

::: {.callout-read title="Packages need to be installed and imported."}
Learn more about using Python packages. How do you find and use packages? What is the difference between installing and importing packages? When do you need to do each one? [This article on Python packages](https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/use-python-packages/) will walk you through the basics.
:::

::: {.content-visible when-format="ipynb"}
:::: {.callout-tip}
To run code in Codespaces, click on the play button in the upper left corner of the code you want to run. You may be asked to "Select a kernel". If you press <kbd>Return</kbd> or click on `base` up at the top, that should select the default kernel.
::::
:::

:::{.callout-task}
The cell below imports several packages you'll need for this challenge. **BUT** there's a problem! To fix it:

  1. Run the cell. What is the error, and what line is triggering it?
  2. Fix the typo that's causing the error
  3. Run the cell again to make sure it's working now
  
:::

```{python}
#| template: student
import geopandas as gpd # Work with vector data
import holoviews as hv # Save maps and plots to files
import hvpolt.pandas # Create interactive maps and plots
from osmnx import features as osm # Search for locations by name
```

::: {.content-visible when-format="html"}
```{python}
#| template: answer
import geopandas as gpd # Work with vector data
import holoviews as hv # Save maps and plots to files
import hvplot.pandas # Create interactive maps and plots
from osmnx import features as osm # Search for locations by name
```
:::
