---
title: Markdown and Project Organization
format:
  html: default
  ipynb:
    output-file: "Get Started with Open Reproducible Science, Part 1!"
---

## Get started with open reproducible science!

[Open reproducible science](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/get-started-open-reproducible-science/) makes scientific methods, data and outcomes available to everyone. That means that *everyone* who wants should be able to **find**, **read**, **understand**, and **run** your workflows for themselves.

![Components of open science represented as layers -- accessible, reproducible, inclusive. [@earth_science_data_systems_open_2021]](https://www.earthdata.nasa.gov/s3fs-public/2021-11/Circle_Diagram_UPDATE_2.jpg?VersionId=pFRniRpjtgc_MEXUJKi9_sXLoMsSX.pB){width=50% fig-align="center" fig-alt="This image is a circular diagram representing the concept of 'Open Science' in a segmented layout. At the center of the circle, the term 'Open Science' is written. The circle is divided into three main sections labeled 'Accessible,' 'Reproducible,' and 'Inclusive.' The 'Accessible' section includes two smaller segments: (1) Open Access to Scientific Publications & Information and (2) Open Data & Software FAIR. The 'Reproducible; section includes three smaller segments: (1) Open Collaborative Analysis Tools, (2) Open Tools Frameworks & Libraries, and (3) New Pathways to Science. The 'Inclusive' section includes three smaller segments: (1) Support Diversity, Equity, & Belonging, (2) Expand Participation & Partnership, and (3) New Pathways to Science. Each segment highlights an aspect of how Open Science aims to be more inclusive, accessible, and reproducible."}

Few if any science projects are 100% open and reproducible (yet!). However, members of the open science community have developed open source tools and practices that can help you move toward that goal. You will learn about many of those tools in [the Intro to Earth Data Science textbook](https://www.earthdatascience.org/courses/intro-to-earth-data-science/). Don't worry about learning all the tools at once -- we've picked a few for you to get started with.

::: {.callout-note icon="false"}
## {{< fa glasses size=large >}} Further reading

Read [our textbook chapter about open reproducible science](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/get-started-open-reproducible-science/).
:::

::: {.cell .markdown}
:::: {.callout-important icon="false"}
## {{< fa pencil size=large >}} What does open reproducible science mean to you?

- [ ] Create a new Markdown cell below this one using the `+ Markdown` button in the upper left.

- [ ] In the new cell, answer the following questions using a **numbered list** in Markdown:

  1.  In 1-2 sentences, define open reproducible science.
  2.  In 1-2 sentences, choose one of the open source tools that you have learned about (i.e. Shell, Git/GitHub, Jupyter Notebook, Python) and explain how it supports open reproducible science.

::::: {.content-visible when-profile="graded"}
Rubric:

| Task | Max Points | Points | Comments |
|------|------------|--------|----------|
| Create Markdown cell              | 1 |  |  |
| Use a numbered list               | 2 |  |  |
| Thoughtful response to question 1 | 2 |  |  |
| Thoughtful response to question 2 | 2 |  |  |
| Easily readable                   | 1 |  |  |
:::::
::::
:::

## Human-readable and Machine-readable

When writing open, reproducible scientific workflows, it is always important to make sure that:

  1. all collaborators can understand what's going on
  2. any commands you give to a computer are clear and unambiguous

We call these two (sometimes competing) goals **human-readability** and **machine-readability**.

::: {.callout-note icon="false"}
## {{< fa glasses size=large >}} Further reading

Read [our textbook chapter about organizing open reproducible science projects](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/get-started-open-reproducible-science/best-practices-for-organizing-open-reproducible-science/).
:::

::: {.cell .markdown}
:::: {.callout-important icon="false"}
## {{< fa pencil size=large >}} Human-readable and Machine-readable

- [ ] Create a new Markdown cell below this one using the <kbd>ESC</kbd> + <kbd>b</kbd> keyboard shortcut.
- [ ] In the new cell, answer the following question in a Markdown **quote**: Does this Jupyter Notebook file have a machine-readable name? Explain your answer.

::::: {.content-visible when-profile="graded"}
Rubric:

| Task | Max Points | Points | Comments |
|------|------------|--------|----------|
| Create Markdown cell            | 1 |  |  |
| Use a quote                     | 2 |  |  |
| Thoughtful response to question | 2 |  |  |
| Easily readable                 | 1 |  |  |
:::::
::::
:::

::: {.callout-important icon="false"}
## {{< fa keyboard size=large >}} Your task: Machine-readable file names

Rename any notebooks in this folder with an **expressive and machine-readable file name**
:::