---
title: "ESA PhenoCam Workshop 2025"
subtitle: "Get started with Environmental Data Science!"
authors:
  - Alison Post
date: last-modified
keywords:
  - "Environmental Data Science"
  - "STEM Education"
aliases: 
  - esa25.html
---

# Welcome to the ESA 2025 PhenoCam Workshop!

This is the curriculum pages for the PhenoCam workshop presented at the 2025 Ecological Society of America meeting held in Baltimore, MD in August 2025. Material includes instructions about how to access PhenoCam data and imagery directly from the website (via API), and how to create greenness timeseries plots, as well as a photo layout and gif showing seasonal changes in a PhenoCam site over the course of a year.

With the exponential increase in available environmental data, researchers often lack the coding skills required to efficiently access and manipulate it. For example, the PhenoCam Network provides data from >700 digital cameras that take regular pictures of ecosystem canopies worldwide. PhenoCam is an impactful teaching and research tool to visualize and study seasonal changes in vegetation across diverse ecosystems and under climate change. While the images and data are available in near-real time on the PhenoCam website, they can be more efficiently accessed and downloaded via several R packages. In this interactive workshop, we’ll demonstrate a low-barrier method to access PhenoCam data via R code using GitHub Classroom and Codespaces. GitHub Classroom allows instructors to set up and share lessons with students through a web-based coding interface (Codespaces). This enables students to quickly start coding without the often-frustrating step of setting up a programming language on their local computers. We’ll walk through an example of GitHub Codespaces using R to access PhenoCam imagery and plot time series of vegetation greenness. This workshop is intended for educators and researchers who want to learn about PhenoCam data and GitHub Codespaces. No prior knowledge of coding or PhenoCam is required.
