---
title: Climate portfolio post
subtitle: Your turn!
jupyter: python3
format:
  ipynb:
    output-file: "Portfolio Post -- Climate Change"
---

::: {.cell .markdown}
## Pick a new location and/or measurement to plot 🌏 📈

Recreate the workflow you just did in a place that interests you OR with a different measurement. You will need to make your own new Markdown and Code cells below this one, or create a new notebook.

Your analysis should include
  - [ ] A researched (with citations or links) **site description**, including *why* you chose the site
  - [ ] A researched (with citations or links) **data description**, including a **data citation**
  - [ ] A researched (with citations or links) **methods overview**
  - [ ] Some kind of **visual evidence** (plot, chart, diagram) for your results
  - [ ] A **headline and description** for the visual evidence that *interprets* your analysis and puts it *in context*

You should also delete the instructions before posting a portfolio page.

---------------------------------------------------------------------
:::

## BONUS: Create a shareable Markdown of your work

Below is some code that you can run that will save a Markdown file of your work that is easily shareable and can be uploaded to GitHub Pages. You can use it as a starting point for writing your portfolio post!

```{python}
%%capture
%%bash
jupyter nbconvert *.ipynb --to markdown
```