---
title: Climate coding challenge, Part 3
jupyter: python3
format:
  ipynb:
    output-file: "Get Started with Open Reproducible Science, Part 3!"
---

# Convert units

::: {.content-visible when-format="ipynb"}
First things first -- make sure to load the climate `DataFrame` you stored in the previous notebooks using Jupyter cell magic:

```{python}
# Load all stored variables
%store -r
```
:::

### For scientific applications, it is often useful to have values in metric units

When you cited the data, you should have noted that temperature was in units of degrees Fahrenheit. Often we want data in metric units, because it makes important calculations (say, sensible heat from temperature) easier. Plus you don't want to be like the [NASA team who crashed a probe into Mars because different teams used different units](https://www.latimes.com/archives/la-xpm-1999-oct-01-mn-17288-story.html))!

::: {.callout-important icon="false"}
# {{< fa keyboard size=large >}} Your task: Save the URL for later

The code below attempts to convert the data to Celcius, using Python mathematical **operators**, like `+`, `-`, `*`, and `/`. Mathematical operators in Python work just like a calculator, and that includes using parentheses to designat the **order of operations**. The equation for converting Fahrenheit temperature to Celcius is:

$$
T_C = (T_F - 32) * \frac{5}{9}
$$

This code is not well documented and doesn't follow [PEP-8 guidelines](https://peps.python.org/pep-0008/#other-recommendations), which has caused the author to miss an **important error**!

```python
dataframe['new_temperature']= dataframe['old_temperature']-32*5/9
dataframe
```

Complete the following steps:
1. [ ] Replace `dataframe` with the name of **your** `DataFrame`.
2. [ ] Replace `'old_temperature'` with the column name **you** used; Replace `'new_temperature'` with an **expressive** column name. 
3. [ ] **THERE IS AN ERROR IN THE CONVERSION - Fix it!**

:::
```{python}
climate_df['TOBS_C'] = (climate_df['TOBS'] - 32) * 5 / 9

climate_df
```

::: {.callout-important icon="false"}
# {{< fa pepper-hot size=large >}} Want an EXTRA CHALLENGE?
Using the code below as a framework, write and apply a **function** that converts to Celcius. You should also rewrite this function name to be more expressive.
  
```python
def convert(temperature):
    """Convert temperature to Celcius"""
    return temperature # Put your equation in here

dataframe['TOBS_C'] = dataframe['TOBS'].apply(convert)
```
:::