name: Quarto Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/quarto-build.yml
    secrets: inherit
    with:
      clear_cache: false
      clear_lockfiles: false
      deploy: true
      cache_salt: stable
